/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class danschirripa_javashell_com_ndi_NDISender */

#ifndef _Included_danschirripa_javashell_com_ndi_NDISender
#define _Included_danschirripa_javashell_com_ndi_NDISender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     danschirripa_javashell_com_ndi_NDISender
 * Method:    initializeNDI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_danschirripa_javashell_com_ndi_NDISender_initializeNDI
  (JNIEnv *, jobject);

/*
 * Class:     danschirripa_javashell_com_ndi_NDISender
 * Method:    sendFrame
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_danschirripa_javashell_com_ndi_NDISender_sendFrame
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
